### ISSUE TITLE
Social links on footer

### ISSUE THREAD

**Issue by NukeManDan** [Cryptorado-Community/Cryptorado-Home#13]
minimal footer with links that use icons only to direct to them:

- [ ] https://keybase.io/team/cryptorado
  - https://fontawesome.com/icons/keybase
- [ ] https://launchpass.com/coloradoblockchain
  - https://material.io/resources/icons/?search=donut&icon=donut_small&style=baseline
- [ ] https://twitter.com/cryptoradocom
  - https://fontawesome.com/icons/twitter
- [ ] https://www.linkedin.com/company/51616656/
  - https://fontawesome.com/icons/linkedin
- [ ] https://www.youtube.com/channel/UCySU1TwgrLAU_1tF8lDt9bQ
  - https://fontawesome.com/icons/youtube
- [ ] https://sites.google.com/view/cryptorado-photos/home
  - https://fontawesome.com/icons/camera-retro
- [ ] https://github.com/Cryptorado-Community/Cryptorado-Home
  - https://fontawesome.com/icons/github

**Comment by surgeon4acure** [comment]
Do you need it in plain HTML/CSS?

**Comment by NukeManDan** [comment]
@surgeon4acure - integrated in Vue using [the quasar footer](https://quasar.dev/layout-builder)
We need the icons to start - wanna add those? :pray:

**Comment by NukeManDan** [comment]
Then (I think) we can integrate with the [icon component](https://quasar.dev/vue-components/icon)

**Comment by surgeon4acure** [comment]
I should be able to do this. I am not familiar with quasar but I've been reading the docs. Is Font Awesome Icons okay for the social links? Or did you have something else in mind.

**Comment by NukeManDan** [comment]
@surgeon4acure - trying to use as few dependencies as possible.  

So I think we should embed them as SVG files.

**Comment by NukeManDan** [comment]
that said, I think we already are using them in quasar. 
https://quasar.dev/vue-components/icon
Let's use this component?

**Comment by NukeManDan** [comment]
Yes - lets use the [QIcon](https://quasar.dev/vue-components/icon) component w/ font awesome & material icons:

Edited the OP to reflect the ones to use @surgeon4acure
