### ISSUE TITLE
Gitcoin grant, issue #79

### ISSUE THREAD

**Issue by DISC30** [Cryptorado-Community/Cryptorado-Home#20]
Found another one @NukeManDan : https://github.com/gitcoinco/gitcoinco/issues/79#issue-595162983

**Comment by NukeManDan** [comment]
Ok - please report this issue to gitcoin: https://github.com/gitcoinco/web/issues

**Comment by NukeManDan** [comment]
Ok - will monitor that issue, thanks @DISC30 for paying attention!

**Comment by DISC30** [comment]
Oh that's the site: https://github.com/gitcoinco/web/issues
geez they've got 1000+ issues there
