### ISSUE TITLE
Feature: Calendar auto-update integration

### ISSUE THREAD

**Issue by NukeManDan** [Cryptorado-Community/Cryptorado-Home#8]
Would be very good to have the event calendar auto update via RSS or other option:

From `https://www.meetup.com/<MEETUPNAME>/events/calendar/`  :
>Subscribe to a feed of this calendar: RSS Atom iCal Outlook
>Subscribe to a feed of RSVPs to this group's Meetups: RSS Atom

So we want:
- [ ] Fetch and update Meetup event listings
- [ ] Fetch and update RSVPS for the events

**Comment by NukeManDan** [comment]
More generic option to integrate : google cal. 

I have this setup and I _think_ integration with present quasar calendar is possible.

**Comment by NukeManDan** [comment]
iframe to do this w/ google:
https://gist.github.com/NukeManDan/03d6fdbd251e294cc3bd24448e3d5b69

**Comment by ryosua** [comment]
If we want to start with the iframe, here's a pr - https://github.com/Cryptorado-Community/Cryptorado-Home/pull/15

**Comment by ryosua** [comment]
Quick recap from the call - 
We are going to just use the Google Calendar iframe to start. The next step that I am working on is loading data from the Google Calendar Api - https://developers.google.com/calendar/v3/reference and using that to load the data using the quasar components.

After that we want a way to let people submit their own events, possibly by prepopulating a github pr that merges their event as JSON into the repo. The calendar could merge the custom event JSON and Google cal JSON together and display as one.

**Comment by ryosua** [comment]
![Annotation 2019-10-20 180420](https://user-images.githubusercontent.com/3247406/67168724-284e2580-f364-11e9-9b94-ee7d58dfc8e7.png)

So it looks like the Google Calendar API is authenticated which means one of us would have to create an account, get an api key, and add that to the repo in order to make requests. 

I would not want to do that because then anyone could see the key and use it to make requests on our behalf.

**Comment by ryosua** [comment]
Or we could have the user sign into Google, and make requests on their behalf - https://developers.google.com/identity/protocols/OAuth2UserAgent

**Comment by NukeManDan** [comment]
It is not possible to access open calendars? We are not doing posts, only gets... the iframe presents the info we need, we just want to consume it differently -> a JSON file, not a GUI.

There must be a way

**Comment by ryosua** [comment]
I can take another look at their docs and see if there is something I'm missing.
